import type { Prisma } from '@prisma/client';

import { prisma } from '@/lib/prisma';
import { mapDecisionToTrackingStatus, type DecisionLabel } from '@/server/services/scoring';

export type RunTrackingPayload = {
  limit?: number;
  statuses?: string[];
};

function mapStatusAlias(status: string): string {
  const v = status.toLowerCase();
  if (v.includes('belum dilacak')) return 'BELUM_DILACAK';
  if (v.includes('perlu verifikasi')) return 'PERLU_VERIFIKASI_MANUAL';
  if (v.includes('teridentifikasi')) return 'TERIDENTIFIKASI';
  if (v.includes('belum ditemukan')) return 'BELUM_DITEMUKAN';
  return status;
}

function asDecisionLabel(value: string): DecisionLabel {
  if (value === 'KEMUNGKINAN_KUAT' || value === 'PERLU_VERIFIKASI' || value === 'TIDAK_COCOK') {
    return value;
  }
  return 'TIDAK_COCOK';
}

export async function runTrackingSimulation(payload: RunTrackingPayload = {}) {
  const statusFilters = (payload.statuses ?? ['Belum Dilacak', 'Perlu Verifikasi Manual']).map(mapStatusAlias);
  const limit = payload.limit ?? 100;

  const targets = await prisma.alumni.findMany({
    where: {
      OR: statusFilters.map((statusPelacakan) => ({ statusPelacakan }))
    },
    take: limit
  });

  let processed = 0;
  let identified = 0;
  let review = 0;
  let notFound = 0;

  await prisma.$transaction(async (tx) => {
    for (const alumni of targets) {
      const top = await tx.disambiguation.findFirst({
        where: { alumniId: alumni.id },
        orderBy: { finalScore: 'desc' },
        include: { candidate: true }
      });

      if (!top) continue;

      const status = mapDecisionToTrackingStatus(asDecisionLabel(top.decisionLabel));
      const now = new Date();
      const latestResult = await tx.trackingResult.findFirst({
        where: { alumniId: alumni.id },
        orderBy: { lastVerifiedAt: 'desc' }
      });

      const payloadData: Prisma.TrackingResultUncheckedCreateInput = {
        id: latestResult?.id ?? `RES-${alumni.id}-${now.getTime()}`,
        alumniId: alumni.id,
        nim: alumni.nim,
        namaLengkap: alumni.namaLengkap,
        prodi: alumni.prodi,
        angkatan: alumni.angkatan,
        trackingStatus: status,
        finalConfidence: top.finalScore,
        matchedCandidateId: top.candidateId,
        topSource: top.candidate.sourceName,
        currentRoleSummary: top.candidate.signalRole,
        currentOrgSummary: top.candidate.signalAffiliation,
        currentLocationSummary: top.candidate.signalLocation,
        evidenceCount: await tx.candidateEvidence.count({ where: { alumniId: alumni.id } }),
        lastVerifiedAt: now,
        notes: `Generated by simulation batch at ${now.toISOString()}`,
        isManuallyVerified: false
      };

      if (latestResult) {
        await tx.trackingResult.update({
          where: { id: latestResult.id },
          data: payloadData
        });
      } else {
        await tx.trackingResult.create({ data: payloadData });
      }

      await tx.alumni.update({
        where: { id: alumni.id },
        data: {
          statusPelacakan: status,
          confidenceScore: top.finalScore,
          sumberTerakhir: top.candidate.sourceName,
          tanggalUpdate: now
        }
      });

      processed += 1;
      if (status === 'TERIDENTIFIKASI') identified += 1;
      if (status === 'PERLU_VERIFIKASI_MANUAL') review += 1;
      if (status === 'BELUM_DITEMUKAN') notFound += 1;
    }
  });

  return {
    processed,
    identified,
    review,
    notFound
  };
}

export async function getTrackingResults(params: { alumniId?: string; status?: string; take?: number }) {
  const { alumniId, status, take = 100 } = params;

  return prisma.trackingResult.findMany({
    where: {
      ...(alumniId ? { alumniId } : {}),
      ...(status ? { trackingStatus: status as any } : {})
    },
    orderBy: { lastVerifiedAt: 'desc' },
    take,
    include: {
      alumni: true
    }
  });
}

export async function verifyResult(id: string, notes?: string) {
  return prisma.trackingResult.update({
    where: { id },
    data: {
      isManuallyVerified: true,
      notes: notes?.trim() ? notes : 'Manual verification completed by reviewer.',
      lastVerifiedAt: new Date()
    }
  });
}
